# Generated by Django 5.2.12 on 2026-03-16 06:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('qr_image', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
